//Build a for loop which starts at 1960 and adds 1 to each year, then using keys
//grab and build the data.

//graphdata.1960.Celtics.wins (the variable will be the year - which will also be stored as array
//Need to collect two points x and y  - x has to be the date
// y will be the data point which will need to be plotted



graphData ={
		  "y1960":{
			  "Celtics":{
			  	"wins":59,
			  	"losses":16,
			  	"ties":0,
			  	"winning%":0.787,
			  	"PF":9337,
			  	"PA":8713,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Bruins":{
			  	"wins":15,
			  	"losses":42,
			  	"ties":13,
			  	"winning%":0.263,
			  	"PF":176,
			  	"PA":254,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":65,
			  	"losses":89,
			  	"ties":0,
			  	"winning%":0.422,
			  	"PF":658,
			  	"PA":775,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":5,
			  	"losses":9,
			  	"ties":0,
			  	"winning%":0.385,
			  	"PF":286,
			  	"PA":349,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  }
		  },
		 "y1961":{
			  "Celtics":{
			  	"wins":57,
			  	"losses":22,
			  	"ties":0,
			  	"winning%":0.722,
			  	"PF":9460,
			  	"PA":9013,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Bruins":{
			  	"wins":15,
			  	"losses":47,
			  	"ties":8,
			  	"winning%":0.242,
			  	"PF":177,
			  	"PA":306,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":76,
			  	"losses":86,
			  	"ties":0,
			  	"winning%":0.469,
			  	"PF":729,
			  	"PA":792,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":9,
			  	"losses":4,
			  	"ties":1,
			  	"winning%":0.692,
			  	"PF":413,
			  	"PA":313,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  }
		  },
		  "y1962":{
			  "Celtics":{
			  	"wins":60,
			  	"losses":20,
			  	"ties":0,
			  	"winning%":0.750,
			  	"PF":9687,
			  	"PA":8948,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Bruins":{
			  	"wins":14,
			  	"losses":39,
			  	"ties":17,
			  	"winning%":0.264,
			  	"PF":198,
			  	"PA":281,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":76,
			  	"losses":84,
			  	"ties":0,
			  	"winning%":0.475,
			  	"PF":707,
			  	"PA":756,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":9,
			  	"losses":4,
			  	"ties":1,
			  	"winning%":0.692,
			  	"PF":346,
			  	"PA":295,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  }
		  },
		  "y1963":{
			  "Celtics":{
			  	"wins":58,
			  	"losses":22,
			  	"ties":0,
			  	"winning%":0.725,
			  	"PF":9504,
			  	"PA":8930,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Bruins":{
			  	"wins":18,
			  	"losses":40,
			  	"ties":12,
			  	"winning%":0.310,
			  	"PF":170,
			  	"PA":212,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":76,
			  	"losses":85,
			  	"ties":0,
			  	"winning%":0.472,
			  	"PF":666,
			  	"PA":704,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":7,
			  	"losses":6,
			  	"ties":1,
			  	"winning%":0.538,
			  	"PF":304,
			  	"PA":257,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			 }
		  },
		  "y1964":{
			  "Celtics":{
			  	"wins":59,
			  	"losses":21,
			  	"ties":0,
			  	"winning%":0.738,
			  	"PF":9042,
			  	"PA":8410,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Bruins":{
			  	"wins":21,
			  	"losses":43,
			  	"ties":6,
			  	"winning%":0.328,
			  	"PF":166,
			  	"PA":253,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":72,
			  	"losses":90,
			  	"ties":0,
			  	"winning%":0.444,
			  	"PF":688,
			  	"PA":793,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":10,
			  	"losses":3,
			  	"ties":1,
			  	"winning%":0.769,
			  	"PF":365,
			  	"PA":297,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y1965":{
			  "Celtics":{
			  	"wins":62,
			  	"losses":18,
			  	"ties":0,
			  	"winning%":0.775,
			  	"PF":9024,
			  	"PA":8353,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Bruins":{
			  	"wins":21,
			  	"losses":43,
			  	"ties":6,
			  	"winning%":0.328,
			  	"PF":166,
			  	"PA":253,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":62,
			  	"losses":100,
			  	"ties":0,
			  	"winning%":0.383,
			  	"PF":669,
			  	"PA":791,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":4,
			  	"losses":8,
			  	"ties":2,
			  	"winning%":0.333,
			  	"PF":244,
			  	"PA":302,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y1966":{
			  "Celtics":{
			  	"wins":54,
			  	"losses":26,
			  	"ties":0,
			  	"winning%":0.675,
			  	"PF":9014,
			  	"PA":8623,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Bruins":{
			  	"wins":17,
			  	"losses":43,
			  	"ties":10,
			  	"winning%":0.283,
			  	"PF":182,
			  	"PA":253,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":72,
			  	"losses":90,
			  	"ties":0,
			  	"winning%":0.444,
			  	"PF":655,
			  	"PA":731,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":8,
			  	"losses":4,
			  	"ties":2,
			  	"winning%":.677,
			  	"PF":315,
			  	"PA":283,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		    "y1967":{
			  "Celtics":{
			  	"wins":60,
			  	"losses":21,
			  	"ties":0,
			  	"winning%":0.741,
			  	"PF":9664,
			  	"PA":9012,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":37,
			  	"losses":27,
			  	"ties":10,
			  	"winning%":0.578,
			  	"PF":259,
			  	"PA":216,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":92,
			  	"losses":70,
			  	"ties":0,
			  	"winning%":0.568,
			  	"PF":722,
			  	"PA":614,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":3,
			  	"losses":10,
			  	"ties":1,
			  	"winning%":0.231,
			  	"PF":280,
			  	"PA":389,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y1968":{
			  "Celtics":{
			  	"wins":54,
			  	"losses":28,
			  	"ties":0,
			  	"winning%":0.659,
			  	"PF":9523,
			  	"PA":9186,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Bruins":{
			  	"wins":42,
			  	"losses":18,
			  	"ties":16,
			  	"winning%":0.700,
			  	"PF":303,
			  	"PA":221,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":86,
			  	"losses":76,
			  	"ties":0,
			  	"winning%":0.531,
			  	"PF":614,
			  	"PA":611,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":4,
			  	"losses":10,
			  	"ties":0,
			  	"winning%":0.286,
			  	"PF":229,
			  	"PA":406,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y1969":{
			  "Celtics":{
			  	"wins":48,
			  	"losses":34,
			  	"ties":0,
			  	"winning%":0.585,
			  	"PF":9102,
			  	"PA":8645,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Bruins":{
			  	"wins":40,
			  	"losses":17,
			  	"ties":19,
			  	"winning%":0.702,
			  	"PF":277,
			  	"PA":216,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Red Sox":{
			  	"wins":87,
			  	"losses":75,
			  	"ties":0,
			  	"winning%":0.537,
			  	"PF":743,
			  	"PA":736,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":4,
			  	"losses":10,
			  	"ties":0,
			  	"winning%":0.286,
			  	"PF":266,
			  	"PA":316,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y1970":{
			  "Celtics":{
			  	"wins":34,
			  	"losses":48,
			  	"ties":0,
			  	"winning%":0.425,
			  	"PF":9422,
			  	"PA":9574,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":57,
			  	"losses":14,
			  	"ties":7,
			  	"winning%":0.803,
			  	"PF":399,
			  	"PA":207,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":87,
			  	"losses":75,
			  	"ties":0,
			  	"winning%":0.537,
			  	"PF":786,
			  	"PA":722,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":2,
			  	"losses":12,
			  	"ties":0,
			  	"winning%":0.231,
			  	"PF":149,
			  	"PA":361,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y1971":{
			  "Celtics":{
			  	"wins":44,
			  	"losses":38,
			  	"ties":0,
			  	"winning%":0.547,
			  	"PF":9608,
			  	"PA":9438,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":54,
			  	"losses":13,
			  	"ties":11,
			  	"winning%":0.806,
			  	"PF":330,
			  	"PA":204,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Red Sox":{
			  	"wins":85,
			  	"losses":77,
			  	"ties":0,
			  	"winning%":0.525,
			  	"PF":691,
			  	"PA":667,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":6,
			  	"losses":8,
			  	"ties":0,
			  	"winning%":0.429,
			  	"PF":238,
			  	"PA":325,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y1972":{
			  "Celtics":{
			  	"wins":56,
			  	"losses":26,
			  	"ties":0,
			  	"winning%":0.683,
			  	"PF":9477,
			  	"PA":9085,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":51,
			  	"losses":22,
			  	"ties":5,
			  	"winning%":0.699,
			  	"PF":349,
			  	"PA":221,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":85,
			  	"losses":70,
			  	"ties":0,
			  	"winning%":0.548,
			  	"PF":640,
			  	"PA":620,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":3,
			  	"losses":11,
			  	"ties":0,
			  	"winning%":0.214,
			  	"PF":192,
			  	"PA":446,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y1973":{
			  "Celtics":{
			  	"wins":68,
			  	"losses":14,
			  	"ties":0,
			  	"winning%":0.829,
			  	"PF":9238,
			  	"PA":8566,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":52,
			  	"losses":17,
			  	"ties":9,
			  	"winning%":0.754,
			  	"PF":349,
			  	"PA":221,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":89,
			  	"losses":73,
			  	"ties":0,
			  	"winning%":0.549,
			  	"PF":89,
			  	"PA":73,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":5,
			  	"losses":9,
			  	"ties":0,
			  	"winning%":0.357,
			  	"PF":258,
			  	"PA":300,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y1974":{
			  "Celtics":{
			  	"wins":56,
			  	"losses":26,
			  	"ties":0,
			  	"winning%":0.683,
			  	"PF":8937,
			  	"PA":8618,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Bruins":{
			  	"wins":40,
			  	"losses":26,
			  	"ties":14,
			  	"winning%":0.606,
			  	"PF":345,
			  	"PA":245,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":84,
			  	"losses":78,
			  	"ties":0,
			  	"winning%":0.519,
			  	"PF":696,
			  	"PA":661,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":7,
			  	"losses":7,
			  	"ties":0,
			  	"winning%":0.500,
			  	"PF":348,
			  	"PA":289,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y1975":{
			  "Celtics":{
			  	"wins":60,
			  	"losses":22,
			  	"ties":0,
			  	"winning%":0.732,
			  	"PF":8734,
			  	"PA":8265,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":48,
			  	"losses":15,
			  	"ties":17,
			  	"winning%":0.762,
			  	"PF":313,
			  	"PA":237,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":95,
			  	"losses":65,
			  	"ties":0,
			  	"winning%":0.594,
			  	"PF":796,
			  	"PA":709,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":3,
			  	"losses":11,
			  	"ties":0,
			  	"winning%":0.214,
			  	"PF":258,
			  	"PA":358,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y1976":{
			  "Celtics":{
			  	"wins":54,
			  	"losses":28,
			  	"ties":0,
			  	"winning%":.659,
			  	"PF":8708,
			  	"PA":8516,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Bruins":{
			  	"wins":49,
			  	"losses":23,
			  	"ties":8,
			  	"winning%":0.681,
			  	"PF":312,
			  	"PA":240,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":83,
			  	"losses":79,
			  	"ties":0,
			  	"winning%":0.512,
			  	"PF":716,
			  	"PA":660,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":11,
			  	"losses":3,
			  	"ties":0,
			  	"winning%":0.786,
			  	"PF":376,
			  	"PA":236,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y1977":{
			  "Celtics":{
			  	"wins":44,
			  	"losses":38,
			  	"ties":0,
			  	"winning%":0.537,
			  	"PF":8572,
			  	"PA":8734,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":51,
			  	"losses":18,
			  	"ties":11,
			  	"winning%":0.739,
			  	"PF":333,
			  	"PA":218,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":97,
			  	"losses":64,
			  	"ties":0,
			  	"winning%":0.602,
			  	"PF":859,
			  	"PA":712,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":9,
			  	"losses":5,
			  	"ties":0,
			  	"winning%":0.643,
			  	"PF":278,
			  	"PA":217,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y1978":{
			  "Celtics":{
			  	"wins":32,
			  	"losses":50,
			  	"ties":0,
			  	"winning%":0.390,
			  	"PF":8670,
			  	"PA":8830,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":43,
			  	"losses":23,
			  	"ties":14,
			  	"winning%":0.652,
			  	"PF":216,
			  	"PA":270,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":99,
			  	"losses":64,
			  	"ties":0,
			  	"winning%":0.607,
			  	"PF":796,
			  	"PA":657,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":11,
			  	"losses":5,
			  	"ties":0,
			  	"winning%":0.688,
			  	"PF":358,
			  	"PA":286,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y1979":{
			  "Celtics":{
			  	"wins":29,
			  	"losses":53,
			  	"ties":0,
			  	"winning%":0.354,
			  	"PF":8874,
			  	"PA":9288,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":46,
			  	"losses":21,
			  	"ties":13,
			  	"winning%":0.687,
			  	"PF":310,
			  	"PA":234,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":91,
			  	"losses":69,
			  	"ties":0,
			  	"winning%":0.569,
			  	"PF":841,
			  	"PA":711,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":9,
			  	"losses":7,
			  	"ties":0,
			  	"winning%":0.563,
			  	"PF":411,
			  	"PA":326,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y1980":{
			  "Celtics":{
			  	"wins":61,
			  	"losses":21,
			  	"ties":0,
			  	"winning%":0.744,
			  	"PF":9303,
			  	"PA":8664,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":37,
			  	"losses":30,
			  	"ties":18,
			  	"winning%":0.552,
			  	"PF":316,
			  	"PA":272,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":83,
			  	"losses":77,
			  	"ties":0,
			  	"winning%":0.519,
			  	"PF":757,
			  	"PA":767,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":10,
			  	"losses":6,
			  	"ties":0,
			  	"winning%":0.625,
			  	"PF":441,
			  	"PA":325,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y1981":{
			  "Celtics":{
			  	"wins":62,
			  	"losses":20,
			  	"ties":0,
			  	"winning%":0.756,
			  	"PF":9008,
			  	"PA":8526,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Bruins":{
			  	"wins":43,
			  	"losses":27,
			  	"ties":10,
			  	"winning%":0.614,
			  	"PF":323,
			  	"PA":285,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":59,
			  	"losses":49,
			  	"ties":0,
			  	"winning%":0.546,
			  	"PF":519,
			  	"PA":481,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":2,
			  	"losses":14,
			  	"ties":0,
			  	"winning%":0.125,
			  	"PF":322,
			  	"PA":370,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y1982":{
			  "Celtics":{
			  	"wins":63,
			  	"losses":19,
			  	"ties":0,
			  	"winning%":0.768,
			  	"PF":9180,
			  	"PA":8657,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":50,
			  	"losses":20,
			  	"ties":10,
			  	"winning%":0.714,
			  	"PF":327,
			  	"PA":228,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":89,
			  	"losses":73,
			  	"ties":0,
			  	"winning%":0.549,
			  	"PF":753,
			  	"PA":713,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":5,
			  	"losses":4,
			  	"ties":0,
			  	"winning%":0.556,
			  	"PF":143,
			  	"PA":157,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y1983":{
			  "Celtics":{
			  	"wins":56,
			  	"losses":26,
			  	"ties":0,
			  	"winning%":0.683,
			  	"PF":9191,
			  	"PA":8752,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":49,
			  	"losses":25,
			  	"ties":6,
			  	"winning%":0.662,
			  	"PF":336,
			  	"PA":261,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":78,
			  	"losses":84,
			  	"ties":0,
			  	"winning%":0.481,
			  	"PF":724,
			  	"PA":771,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":8,
			  	"losses":8,
			  	"ties":0,
			  	"winning%":0.500,
			  	"PF":274,
			  	"PA":289,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y1984":{
			  "Celtics":{
			  	"wins":62,
			  	"losses":20,
			  	"ties":0,
			  	"winning%":0.756,
			  	"PF":9194,
			  	"PA":2143,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Bruins":{
			  	"wins":36,
			  	"losses":34,
			  	"ties":10,
			  	"winning%":0.514,
			  	"PF":303,
			  	"PA":287,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":86,
			  	"losses":76,
			  	"ties":0,
			  	"winning%":0.531,
			  	"PF":810,
			  	"PA":764,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":9,
			  	"losses":7,
			  	"ties":0,
			  	"winning%":0.563,
			  	"PF":362,
			  	"PA":352,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y1985":{
			  "Celtics":{
			  	"wins":63,
			  	"losses":19,
			  	"ties":0,
			  	"winning%":0.768,
			  	"PF":9412,
			  	"PA":8867,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":37,
			  	"losses":31,
			  	"ties":12,
			  	"winning%":0.544,
			  	"PF":311,
			  	"PA":288,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":81,
			  	"losses":81,
			  	"ties":0,
			  	"winning%":0.500,
			  	"PF":800,
			  	"PA":720,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":11,
			  	"losses":5,
			  	"ties":0,
			  	"winning%":0.688,
			  	"PF":362,
			  	"PA":290,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			 }
		  },
		   "y1986":{
			  "Celtics":{
			  	"wins":67,
			  	"losses":15,
			  	"ties":0,
			  	"winning%":0.817,
			  	"PF":9359,
			  	"PA":8587,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Bruins":{
			  	"wins":39,
			  	"losses":34,
			  	"ties":7,
			  	"winning%":0.534,
			  	"PF":301,
			  	"PA":276,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":95,
			  	"losses":66,
			  	"ties":0,
			  	"winning%":0.590,
			  	"PF":794,
			  	"PA":696,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":11,
			  	"losses":5,
			  	"ties":0,
			  	"winning%":0.688,
			  	"PF":412,
			  	"PA":307,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y1987":{
			  "Celtics":{
			  	"wins":59,
			  	"losses":23,
			  	"ties":0,
			  	"winning%":0.720,
			  	"PF":9237,
			  	"PA":8692,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":44,
			  	"losses":30,
			  	"ties":6,
			  	"winning%":0.595,
			  	"PF":300,
			  	"PA":251,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":78,
			  	"losses":84,
			  	"ties":0,
			  	"winning%":0.481,
			  	"PF":842,
			  	"PA":825,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":8,
			  	"losses":7,
			  	"ties":0,
			  	"winning%":0.533,
			  	"PF":320,
			  	"PA":293,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y1988":{
			  "Celtics":{
			  	"wins":57,
			  	"losses":25,
			  	"ties":0,
			  	"winning%":0.695,
			  	"PF":9315,
			  	"PA":8828,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":37,
			  	"losses":29,
			  	"ties":14,
			  	"winning%":0.561,
			  	"PF":289,
			  	"PA":256,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":89,
			  	"losses":73,
			  	"ties":0,
			  	"winning%":0.549,
			  	"PF":813,
			  	"PA":689,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":9,
			  	"losses":7,
			  	"ties":0,
			  	"winning%":0.563,
			  	"PF":250,
			  	"PA":284,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y1989":{
			  "Celtics":{
			  	"wins":42,
			  	"losses":40,
			  	"ties":0,
			  	"winning%":0.512,
			  	"PF":8958,
			  	"PA":8863,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":46,
			  	"losses":25,
			  	"ties":9,
			  	"winning%":0.613,
			  	"PF":289,
			  	"PA":232,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":83,
			  	"losses":79,
			  	"ties":0,
			  	"winning%":0.512,
			  	"PF":774,
			  	"PA":735,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":5,
			  	"losses":11,
			  	"ties":0,
			  	"winning%":0.313,
			  	"PF":297,
			  	"PA":391,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y1990":{
			  "Celtics":{
			  	"wins":52,
			  	"losses":30,
			  	"ties":0,
			  	"winning%":0.634,
			  	"PF":9023,
			  	"PA":8696,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":44,
			  	"losses":24,
			  	"ties":12,
			  	"winning%":0.647,
			  	"PF":299,
			  	"PA":264,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":88,
			  	"losses":74,
			  	"ties":0,
			  	"winning%":0.543,
			  	"PF":699,
			  	"PA":664,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":1,
			  	"losses":15,
			  	"ties":0,
			  	"winning%":0.063,
			  	"PF":181,
			  	"PA":446,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y1991":{
			  "Celtics":{
			  	"wins":56,
			  	"losses":26,
			  	"ties":0,
			  	"winning%":0.683,
			  	"PF":9145,
			  	"PA":8668,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":36,
			  	"losses":32,
			  	"ties":12,
			  	"winning%":0.529,
			  	"PF":270,
			  	"PA":275,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":84,
			  	"losses":78,
			  	"ties":0,
			  	"winning%":0.519,
			  	"PF":731,
			  	"PA":712,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":6,
			  	"losses":10,
			  	"ties":0,
			  	"winning%":0.375,
			  	"PF":211,
			  	"PA":305,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y1992":{
			  "Celtics":{
			  	"wins":51,
			  	"losses":31,
			  	"ties":0,
			  	"winning%":0.622,
			  	"PF":8745,
			  	"PA":8448,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":51,
			  	"losses":26,
			  	"ties":7,
			  	"winning%":0.662,
			  	"PF":332,
			  	"PA":268,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":73,
			  	"losses":89,
			  	"ties":0,
			  	"winning%":0.451,
			  	"PF":589,
			  	"PA":669,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":2,
			  	"losses":14,
			  	"ties":0,
			  	"winning%":0.125,
			  	"PF":205,
			  	"PA":363,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y1993":{
			  "Celtics":{
			  	"wins":48,
			  	"losses":34,
			  	"ties":0,
			  	"winning%":0.585,
			  	"PF":8502,
			  	"PA":8429,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":42,
			  	"losses":29,
			  	"ties":13,
			  	"winning%":0.592,
			  	"PF":289,
			  	"PA":252,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":80,
			  	"losses":82,
			  	"ties":0,
			  	"winning%":0.494,
			  	"PF":686,
			  	"PA":698,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":5,
			  	"losses":11,
			  	"ties":0,
			  	"winning%":0.313,
			  	"PF":238,
			  	"PA":286,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y1994":{
			  "Celtics":{
			  	"wins":35,
			  	"losses":20,
			  	"ties":0,
			  	"winning%":0.390,
			  	"PF":8267,
			  	"PA":8618,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":27,
			  	"losses":18,
			  	"ties":3,
			  	"winning%":0.600,
			  	"PF":150,
			  	"PA":127,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":54,
			  	"losses":61,
			  	"ties":0,
			  	"winning%":0.470,
			  	"PF":552,
			  	"PA":621,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":10,
			  	"losses":6,
			  	"ties":0,
			  	"winning%":0.625,
			  	"PF":351,
			  	"PA":312,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y1995":{
			  "Celtics":{
			  	"wins":35,
			  	"losses":47,
			  	"ties":0,
			  	"winning%":0.427,
			  	"PF":8428,
			  	"PA":8582,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":40,
			  	"losses":31,
			  	"ties":11,
			  	"winning%":0.563,
			  	"PF":282,
			  	"PA":269,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":86,
			  	"losses":58,
			  	"ties":0,
			  	"winning%":0.597,
			  	"PF":791,
			  	"PA":698,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":6,
			  	"losses":10,
			  	"ties":0,
			  	"winning%":0.375,
			  	"PF":294,
			  	"PA":377,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y1996":{
			  "Celtics":{
			  	"wins":33,
			  	"losses":49,
			  	"ties":0,
			  	"winning%":0.402,
			  	"PF":8495,
			  	"PA":8774,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":26,
			  	"losses":47,
			  	"ties":9,
			  	"winning%":0.356,
			  	"PF":234,
			  	"PA":300,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":85,
			  	"losses":77,
			  	"ties":0,
			  	"winning%":0.525,
			  	"PF":928,
			  	"PA":921,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":11,
			  	"losses":6,
			  	"ties":0,
			  	"winning%":0.688,
			  	"PF":418,
			  	"PA":313,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			 }
		  },
		  "y1997":{
			  "Celtics":{
			  	"wins":15,
			  	"losses":67,
			  	"ties":0,
			  	"winning%":0.183,
			  	"PF":8248,
			  	"PA":8849,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":39,
			  	"losses":30,
			  	"ties":13,
			  	"winning%":0.565,
			  	"PF":221,
			  	"PA":194,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":78,
			  	"losses":84,
			  	"ties":0,
			  	"winning%":0.481,
			  	"PF":851,
			  	"PA":857,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":10,
			  	"losses":6,
			  	"ties":0,
			  	"winning%":0.625,
			  	"PF":369,
			  	"PA":289,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y1998":{
			  "Celtics":{
			  	"wins":36,
			  	"losses":46,
			  	"ties":0,
			  	"winning%":0.439,
			  	"PF":7864,
			  	"PA":8079,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":39,
			  	"losses":30,
			  	"ties":13,
			  	"winning%":0.565,
			  	"PF":214,
			  	"PA":181,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":92,
			  	"losses":70,
			  	"ties":0,
			  	"winning%":0.568,
			  	"PF":876,
			  	"PA":729,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":9,
			  	"losses":7,
			  	"ties":0,
			  	"winning%":0.563,
			  	"PF":337,
			  	"PA":329,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		    "y1999":{
			  "Celtics":{
			  	"wins":19,
			  	"losses":39,
			  	"ties":0,
			  	"winning%":0.380,
			  	"PF":4650,
			  	"PA":4743,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":24,
			  	"losses":33,
			  	"ties":19,
			  	"winning%":0.421,
			  	"PF":210,
			  	"PA":248,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":94,
			  	"losses":68,
			  	"ties":0,
			  	"winning%":0.580,
			  	"PF":836,
			  	"PA":718,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":8,
			  	"losses":8,
			  	"ties":0,
			  	"winning%":0.500,
			  	"PF":299,
			  	"PA":284,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y2000":{
			  "Celtics":{
			  	"wins":35,
			  	"losses":47,
			  	"ties":0,
			  	"winning%":0.427,
			  	"PF":8146,
			  	"PA":8203,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":36,
			  	"losses":30,
			  	"ties":8,
			  	"winning%":0.545,
			  	"PF":227,
			  	"PA":249,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":85,
			  	"losses":77,
			  	"ties":0,
			  	"winning%":0.525,
			  	"PF":792,
			  	"PA":745,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":5,
			  	"losses":11,
			  	"ties":0,
			  	"winning%":0.313,
			  	"PF":276,
			  	"PA":338,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y2001":{
			  "Celtics":{
			  	"wins":36,
			  	"losses":46,
			  	"ties":0,
			  	"winning%":0.439,
			  	"PF":7759,
			  	"PA":7934,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":43,
			  	"losses":24,
			  	"ties":6,
			  	"winning%":0.642,
			  	"PF":236,
			  	"PA":231,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":82,
			  	"losses":79,
			  	"ties":0,
			  	"winning%":0.509,
			  	"PF":772,
			  	"PA":745,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":11,
			  	"losses":5,
			  	"ties":0,
			  	"winning%":0.688,
			  	"PF":371,
			  	"PA":272,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			 }
		  },
		    "y2002":{
			  "Celtics":{
			  	"wins":49,
			  	"losses":33,
			  	"ties":0,
			  	"winning%":0.598,
			  	"PF":7901,
			  	"PA":7720,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":36,
			  	"losses":31,
			  	"ties":11,
			  	"winning%":0.531,
			  	"PF":245,
			  	"PA":237,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":93,
			  	"losses":69,
			  	"ties":0,
			  	"winning%":0.574,
			  	"PF":859,
			  	"PA":665,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":9,
			  	"losses":7,
			  	"ties":0,
			  	"winning%":0.562,
			  	"PF":381,
			  	"PA":346,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		   "y2003":{
			  "Celtics":{
			  	"wins":44,
			  	"losses":38,
			  	"ties":0,
			  	"winning%":0.537,
			  	"PF":7599,
			  	"PA":7631,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":41,
			  	"losses":19,
			  	"ties":15,
			  	"winning%":0.683,
			  	"PF":209,
			  	"PA":188,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":95,
			  	"losses":67,
			  	"ties":0,
			  	"winning%":0.586,
			  	"PF":961,
			  	"PA":809,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":14,
			  	"losses":2,
			  	"ties":0,
			  	"winning%":0.875,
			  	"PF":348,
			  	"PA":238,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			 }
		  },
		  "y2004":{
			  "Celtics":{
			  	"wins":36,
			  	"losses":46,
			  	"ties":0,
			  	"winning%":0.439,
			  	"PF":7811,
			  	"PA":7930,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":0,
			  	"losses":0,
			  	"ties":0,
			  	"winning%":0,
			  	"PF":0,
			  	"PA":0,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":98,
			  	"losses":64,
			  	"ties":0,
			  	"winning%":0.605,
			  	"PF":949,
			  	"PA":768,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Patriots":{
			  	"wins":14,
			  	"losses":2,
			  	"ties":0,
			  	"winning%":0.875,
			  	"PF":437,
			  	"PA":260,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			 }
		  },
		  "y2005":{
		     "Celtics":{
			  	"wins":45,
			  	"losses":37,
			  	"ties":0,
			  	"winning%":0.549,
			  	"PF":8304,
			  	"PA":8233,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":29,
			  	"losses":37,
			  	"ties":0,
			  	"winning%":0.439,
			  	"PF":230,
			  	"PA":266,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":95,
			  	"losses":67,
			  	"ties":0,
			  	"winning%":0.589,
			  	"PF":910,
			  	"PA":805,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":10,
			  	"losses":6,
			  	"ties":0,
			  	"winning%":0.625,
			  	"PF":379,
			  	"PA":338,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y2006":{
			  "Celtics":{
			  	"wins":33,
			  	"losses":49,
			  	"ties":0,
			  	"winning%":0.402,
			  	"PF":8033,
			  	"PA":8159,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":35,
			  	"losses":41,
			  	"ties":0,
			  	"winning%":0.461,
			  	"PF":219,
			  	"PA":289,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":86,
			  	"losses":76,
			  	"ties":0,
			  	"winning%":0.531,
			  	"PF":820,
			  	"PA":825,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":12,
			  	"losses":4,
			  	"ties":0,
			  	"winning%":0.750,
			  	"PF":385,
			  	"PA":237,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			 }
		  },
		  "y2007":{
			  "Celtics":{
			  	"wins":24,
			  	"losses":58,
			  	"ties":0,
			  	"winning%":0.293,
			  	"PF":7857,
			  	"PA":8137,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":41,
			  	"losses":29,
			  	"ties":0,
			  	"winning%":0.586,
			  	"PF":212,
			  	"PA":222,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":96,
			  	"losses":66,
			  	"ties":0,
			  	"winning%":0.593,
			  	"PF":867,
			  	"PA":657,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Patriots":{
			  	"wins":16,
			  	"losses":0,
			  	"ties":0,
			  	"winning%":1.00,
			  	"PF":589,
			  	"PA":274,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			 }
		  },
		  "y2008":{
			  "Celtics":{
			  	"wins":66,
			  	"losses":16,
			  	"ties":0,
			  	"winning%":0.805,
			  	"PF":8245,
			  	"PA":7404,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Bruins":{
			  	"wins":53,
			  	"losses":19,
			  	"ties":0,
			  	"winning%":0.736,
			  	"PF":274,
			  	"PA":196,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":95,
			  	"losses":67,
			  	"ties":0,
			  	"winning%":0.586,
			  	"PF":845,
			  	"PA":694,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":11,
			  	"losses":5,
			  	"ties":0,
			  	"winning%":0.583,
			  	"PF":410,
			  	"PA":309,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y2009":{
			  "Celtics":{
			  	"wins":62,
			  	"losses":20,
			  	"ties":0,
			  	"winning%":0.756,
			  	"PF":8275,
			  	"PA":7659,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":39,
			  	"losses":30,
			  	"ties":0,
			  	"winning%":0.565,
			  	"PF":206,
			  	"PA":200,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":95,
			  	"losses":67,
			  	"ties":0,
			  	"winning%":0.586,
			  	"PF":872,
			  	"PA":736,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":10,
			  	"losses":6,
			  	"ties":0,
			  	"winning%":0.625,
			  	"PF":427,
			  	"PA":285,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y2010":{
			  "Celtics":{
			  	"wins":50,
			  	"losses":32,
			  	"ties":0,
			  	"winning%":0.610,
			  	"PF":8136,
			  	"PA":7836,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":46,
			  	"losses":25,
			  	"ties":0,
			  	"winning%":0.648,
			  	"PF":246,
			  	"PA":195,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Red Sox":{
			  	"wins":89,
			  	"losses":73,
			  	"ties":0,
			  	"winning%":0.549,
			  	"PF":818,
			  	"PA":744,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":14,
			  	"losses":2,
			  	"ties":0,
			  	"winning%":0.875,
			  	"PF":518,
			  	"PA":313,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			 }
		  },
		  "y2011":{
			  "Celtics":{
			  	"wins":56,
			  	"losses":26,
			  	"ties":0,
			  	"winning%":0.683,
			  	"PF":7913,
			  	"PA":7473,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":49,
			  	"losses":29,
			  	"ties":0,
			  	"winning%":0.628,
			  	"PF":269,
			  	"PA":202,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":90,
			  	"losses":72,
			  	"ties":0,
			  	"winning%":0.556,
			  	"PF":875,
			  	"PA":737,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":13,
			  	"losses":3,
			  	"ties":0,
			  	"winning%":0.813,
			  	"PF":513,
			  	"PA":342,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			 }
		  },
		   "y2012":{
			  "Celtics":{
			  	"wins":39,
			  	"losses":27,
			  	"ties":0,
			  	"winning%":0.591,
			  	"PF":6062,
			  	"PA":5896,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":28,
			  	"losses":14,
			  	"ties":0,
			  	"winning%":0.667,
			  	"PF":131,
			  	"PA":109,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":69,
			  	"losses":93,
			  	"ties":0,
			  	"winning%":0.426,
			  	"PF":734,
			  	"PA":806,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":12,
			  	"losses":4,
			  	"ties":0,
			  	"winning%":0.750,
			  	"PF":557,
			  	"PA":331,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			 }
		  },
		  "y2013":{
			  "Celtics":{
			  	"wins":41,
			  	"losses":40,
			  	"ties":0,
			  	"winning%":0.506,
			  	"PF":7818,
			  	"PA":7836,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":54,
			  	"losses":19,
			  	"ties":0,
			  	"winning%":0.740,
			  	"PF":261,
			  	"PA":177,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":97,
			  	"losses":65,
			  	"ties":0,
			  	"winning%":0.599,
			  	"PF":853,
			  	"PA":656,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			  },
			  "Patriots":{
			  	"wins":12,
			  	"losses":4,
			  	"ties":0,
			  	"winning%":0.750,
			  	"PF":444,
			  	"PA":338,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			 }
		  },
		  "y2014":{
			  "Celtics":{
			  	"wins":25,
			  	"losses":37,
			  	"ties":0,
			  	"winning%":0.305,
			  	"PF":7892,
			  	"PA":8258,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":41,
			  	"losses":27,
			  	"ties":0,
			  	"winning%":0.607,
			  	"PF":213,
			  	"PA":211,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":71,
			  	"losses":91,
			  	"ties":0,
			  	"winning%":0.438,
			  	"PF":634,
			  	"PA":715,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":12,
			  	"losses":4,
			  	"ties":0,
			  	"winning%":0.750,
			  	"PF":468,
			  	"PA":313,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":1
			 }
		  },
		   "y2015":{
			  "Celtics":{
			  	"wins":40,
			  	"losses":42,
			  	"ties":0,
			  	"winning%":0.488,
			  	"PF":8312,
			  	"PA":8299,
			  	"playoffs":1,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Bruins":{
			  	"wins":32,
			  	"losses":22,
			  	"ties":0,
			  	"winning%":0.593,
			  	"PF":185,
			  	"PA":169,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Red Sox":{
			  	"wins":78,
			  	"losses":84,
			  	"ties":0,
			  	"winning%":0.481,
			  	"PF":748,
			  	"PA":753,
			  	"playoffs":0,
			  	"conf_finals":0,
			  	"championship":0
			  },
			  "Patriots":{
			  	"wins":12,
			  	"losses":4,
			  	"ties":0,
			  	"winning%":0.750,
			  	"PF":465,
			  	"PA":315,
			  	"playoffs":1,
			  	"conf_finals":1,
			  	"championship":0
			}
		}
}
